/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tela;

import br.com.entidade.EMarca;
import br.com.generics.GeradorID;
import br.com.negocio.NMarca;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class CadastroMarcas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMarcas
     */
    EMarca oEMarca;
    GeradorID oGeradorID;
    
    //ALTERAR CAMINHO DO ARQUIVO
    private final String arquivoMarca = "/home/bruno/DadosMarcas.txt";

    public CadastroMarcas() {
        initComponents();
        jScrollPane1.setVisible(false);
        jButtonConsultarMarca.setEnabled(true);
        this.jButtonExcluirMarca.setEnabled(false);
    }

    public void organizarTable() {

        try {
            NMarca oNMarca = new NMarca(arquivoMarca);
            ArrayList<EMarca> listaMarcas;
            listaMarcas = oNMarca.listagem();
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Código");
            modelo.addColumn("Descrição");

            if (listaMarcas.isEmpty()) {
                modelo.addRow(new String[]{"Nenhum valor encontrado", "Nenhum valor encontrado"});
            } else {
                listaMarcas.stream().map((marca) -> marca.desmaterializar().split(";")).forEachOrdered((dados) -> {
                    modelo.addRow(dados);
                });
            }
            jTable1.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescricaoMarca = new javax.swing.JTextField();
        jButtonIncluirMarca = new javax.swing.JButton();
        jButtonConsultarMarca = new javax.swing.JButton();
        jButtonExcluirMarca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cadastro Marcas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 12, -1, -1));

        jLabel2.setText("Descrição:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 69, -1, -1));

        jTextFieldDescricaoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescricaoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 64, 121, -1));

        jButtonIncluirMarca.setText("Incluir");
        jButtonIncluirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluirMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 128, -1, -1));

        jButtonConsultarMarca.setText("Consultar");
        jButtonConsultarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 128, -1, -1));

        jButtonExcluirMarca.setText("Excluir");
        jButtonExcluirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 128, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, 103));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescricaoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoMarcaActionPerformed

    private void jButtonIncluirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirMarcaActionPerformed
        try {
            oEMarca = new EMarca();
            oGeradorID = new GeradorID();
            NMarca oNmarca = new NMarca(arquivoMarca);

            oEMarca.setDescricaoMarca(jTextFieldDescricaoMarca.getText().toUpperCase().trim());
            oEMarca.setIdMarca(oGeradorID.getIdentificadorContato());

            oNmarca.incluir(oEMarca);

            oGeradorID.finalize();

            jTextFieldDescricaoMarca.setText(null);
            JOptionPane.showMessageDialog(rootPane, "Marca incluída com sucesso");
            this.organizarTable();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_jButtonIncluirMarcaActionPerformed

    private void jButtonExcluirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirMarcaActionPerformed
        try {
            String dados = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            
            NMarca oNMarca = new NMarca(arquivoMarca);
            oNMarca.excluir(dados);
            this.organizarTable();
            this.jButtonExcluirMarca.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_jButtonExcluirMarcaActionPerformed

    private void jButtonConsultarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarMarcaActionPerformed

        jScrollPane1.setVisible(true);
        jTable1.setLocation(rootPane.getWidth(),rootPane.getHeight() - 50);
        jButtonConsultarMarca.setEnabled(false);
        this.organizarTable();
    }//GEN-LAST:event_jButtonConsultarMarcaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.jButtonExcluirMarca.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMarcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMarcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarMarca;
    private javax.swing.JButton jButtonExcluirMarca;
    private javax.swing.JButton jButtonIncluirMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDescricaoMarca;
    // End of variables declaration//GEN-END:variables
}
